name: Generate Properties

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
      remarks:
        required: true
      domain:
        required: true
      project_name:
        required: true
      onboarding_project_name:
        required: true
      job_name:
        required: true
      int_details_json:
        description: "Paste raw JSON"
        required: true
      target_branch:
        default: "feature/initial_load"
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create / reset feature branch
        run: |
          git checkout -B ${{ github.event.inputs.target_branch }}

      - name: Generate properties
        env:
          ENV: ${{ github.event.inputs.env }}
          REMARKS: ${{ github.event.inputs.remarks }}
          DOMAIN: ${{ github.event.inputs.domain }}
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
          ONBOARDING_PROJECT_NAME: ${{ github.event.inputs.onboarding_project_name }}
          JOB_NAME: ${{ github.event.inputs.job_name }}
          INT_DETAILS_JSON: ${{ github.event.inputs.int_details_json }}
        run: |
          python scripts/generate_properties.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add ${{ github.event.inputs.env }}.properties
          git commit -m "Add ${{ github.event.inputs.env }} properties" || echo "Nothing to commit"

          git push origin ${{ github.event.inputs.target_branch }} --force-with-lease
